name: Lint PR

on:
  # Triggers the workflow on any pull request (but runs in context of target branch, having a bit higher rights)
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  title:
    name: Validate PR title
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          headerPattern: '^\[(\w*)\]:?\s*(.*)$'
          headerPatternCorrespondence: type, subject
          types: |
            FEATURE
            ADD
            CHANGE
            REMOVE
            FIX
            REFACTOR
            DEV
            CHORE
